{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jupiter.serviceAccountName" . }}
  labels:
{{ include "jupiter.labels" . | indent 4 }}
{{- end -}}
